/*Generated this with with a python script I wrote. I included the file in the mockdata dir. */

const SampleProductsGen =  [
	{
		id: "0",
		name:  "Apple",
		displayname:  "Apple",
		price:  "$99.99",
		desc: "A great Apple.", 
	},
	{
		id: "1",
		name:  "AppleWorm",
		displayname:  "apple",
		price:  "$0.59",
		desc: "An okay apple.", 
	},
	{
		id: "2",
		name:  "Avocado",
		displayname:  "Avocado",
		price:  "$2.99",
		desc: "Grown in Michigan.", 
	},
	{
		id: "3",
		name:  "Bacon",
		displayname:  "Bacon",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "4",
		name:  "Beer",
		displayname:  "Beer",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "5",
		name:  "Boar",
		displayname:  "Boar",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "6",
		name:  "Bread",
		displayname:  "Bread",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "7",
		name:  "Brownie",
		displayname:  "Brownie",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "8",
		name:  "Bug",
		displayname:  "Bug",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "9",
		name:  "Cheese",
		displayname:  "Cheese",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "10",
		name:  "Cherry",
		displayname:  "Cherry",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "11",
		name:  "Chicken",
		displayname:  "Chicken",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "12",
		name:  "ChickenLeg",
		displayname:  "ChickenLeg",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "13",
		name:  "Cookie",
		displayname:  "Cookie",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "14",
		name:  "DragonFruit",
		displayname:  "DragonFruit",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "15",
		name:  "Eggplant",
		displayname:  "Eggplant",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "16",
		name:  "Eggs",
		displayname:  "Eggs",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "17",
		name:  "Fish",
		displayname:  "Fish",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "18",
		name:  "FishFillet",
		displayname:  "FishFillet",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "19",
		name:  "FishSteak",
		displayname:  "FishSteak",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "20",
		name:  "Grub",
		displayname:  "Grub",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "21",
		name:  "Grubs",
		displayname:  "Grubs",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "22",
		name:  "Honey",
		displayname:  "Honey",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "23",
		name:  "Honeycomb",
		displayname:  "Honeycomb",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "24",
		name:  "Jam",
		displayname:  "Jam",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "25",
		name:  "Jerky",
		displayname:  "Jerky",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "26",
		name:  "Lemon",
		displayname:  "Lemon",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "27",
		name:  "Marmalade",
		displayname:  "Marmalade",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "28",
		name:  "MelonCantaloupe",
		displayname:  "MelonCantaloupe",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "29",
		name:  "MelonHoneydew",
		displayname:  "MelonHoneydew",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "30",
		name:  "MelonWater",
		displayname:  "MelonWater",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "31",
		name:  "Moonshine",
		displayname:  "Moonshine",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "32",
		name:  "Olive",
		displayname:  "Olive",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "33",
		name:  "Onion",
		displayname:  "Onion",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "34",
		name:  "Peach",
		displayname:  "Peach",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "35",
		name:  "PepperGreen",
		displayname:  "PepperGreen",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "36",
		name:  "PepperRed",
		displayname:  "PepperRed",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "37",
		name:  "Pepperoni",
		displayname:  "Pepperoni",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "38",
		name:  "PickledEggs",
		displayname:  "PickledEggs",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "39",
		name:  "PieApple",
		displayname:  "PieApple",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "40",
		name:  "PieLemon",
		displayname:  "PieLemon",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "41",
		name:  "PiePumpkin",
		displayname:  "PiePumpkin",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "42",
		name:  "Pineapple",
		displayname:  "Pineapple",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "43",
		name:  "Potato",
		displayname:  "Potato",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "44",
		name:  "PotatoRed",
		displayname:  "PotatoRed",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "45",
		name:  "Pretzel",
		displayname:  "Pretzel",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "46",
		name:  "Ribs",
		displayname:  "Ribs",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "47",
		name:  "Roll",
		displayname:  "Roll",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "48",
		name:  "Saki",
		displayname:  "Saki",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "49",
		name:  "Sardines",
		displayname:  "Sardines",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "50",
		name:  "Sashimi",
		displayname:  "Sashimi",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "51",
		name:  "Shrimp",
		displayname:  "Shrimp",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "52",
		name:  "Steak",
		displayname:  "Steak",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "53",
		name:  "Stein",
		displayname:  "Stein",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "54",
		name:  "Strawberry",
		displayname:  "Strawberry",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "55",
		name:  "Sushi",
		displayname:  "Sushi",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "56",
		name:  "Tart",
		displayname:  "Tart",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "57",
		name:  "Tomato",
		displayname:  "Tomato",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "58",
		name:  "Turnip",
		displayname:  "Turnip",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "59",
		name:  "Waffles",
		displayname:  "Waffles",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "60",
		name:  "Whiskey",
		displayname:  "Whiskey",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
	{
		id: "61",
		name:  "Wine",
		displayname:  "Wine",
		price:  "$99.99",
		desc: "An incredible product.", 
	},
]

export default SampleProductsGen