/*Generated this with with a python script I wrote. I included the file in the mockdata dir. */

const SampleProductsGen =  [
	{
		id: 0,
		name:  "Apple",
		displayname:  "Apple",
		price:  99.99,
		desc: "A great Apple.",
		category: "Fruits/Vegetables",
	},
	{
		id: 1,
		name:  "Apple Pie",
		displayname:  "Apple Pie",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 2,
		name:  "Avocado",
		displayname:  "Avocado",
		price:  2.99,
		desc: "Grown in Michigan.",
		category: "Fruits/Vegetables",
	},
	{
		id: 3,
		name:  "Bacon",
		displayname:  "Bacon",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 4,
		name:  "Beer",
		displayname:  "Beer",
		price:  99.99,
		desc: "An incredible product.",
		category: "Beverages",
	},
	{
		id: 5,
		name: "Bellpepper",
		displayname: "Bellpepper",
		price: 99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 6,
		name:  "Boar",
		displayname:  "Boar",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 7,
		name:  "Bread",
		displayname:  "Bread",
		price:  99.99,
		desc: "An incredible product.",
		category: "???",
	},
	{
		id: 8,
		name:  "Brownie",
		displayname:  "Brownie",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 9,
		name: "Cantaloupe",
		displayname: "Cantaloupe",
		price: 99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 10,
		name:  "Cheese",
		displayname:  "Cheese",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 11,
		name:  "Cherry",
		displayname:  "Cherry",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables"
	},
	{
		id: 12,
		name:  "Chicken",
		displayname:  "Chicken",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 13,
		name:  "Chicken Leg",
		displayname:  "Chicken Leg",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 14,
		name:  "Cookie",
		displayname:  "Cookie",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 15,
		name:  "Dragonfruit",
		displayname:  "Dragonfruit",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 16,
		name:  "Egg",
		displayname:  "Egg",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 17,
		name:  "Eggplant",
		displayname:  "Eggplant",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 18,
		name:  "Fish",
		displayname:  "Fish",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 19,
		name:  "Honey",
		displayname:  "Honey",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 20,
		name:  "Honeycomb",
		displayname:  "Honeycomb",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 21,
		name: "Honeydew",
		displayname: "Honeydew",
		price: 99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 22,
		name:  "Jam",
		displayname:  "Jam",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 23,
		name:  "Jerky",
		displayname:  "Jerky",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 24,
		name:  "Lemon",
		displayname:  "Lemon",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 25,
		name:  "Lemon Pie",
		displayname:  "Lemon Pie",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 26,
		name:  "Marmalade",
		displayname:  "Marmalade",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 27,
		name:  "Olives",
		displayname:  "Olives",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 28,
		name:  "Onion",
		displayname:  "Onion",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 29,
		name:  "Peach",
		displayname:  "Peach",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 30,
		name:  "Pepperoni",
		displayname:  "Pepperoni",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 31,
		name:  "Pineapple",
		displayname:  "Pineapple",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 32,
		name:  "Potato",
		displayname:  "Potato",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 33,
		name:  "Pretzels",
		displayname:  "Pretzels",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 34,
		name:  "Pumpkin Pie",
		displayname:  "Pumpkin Pie",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 35,
		name:  "Red Bellpepper",
		displayname:  "Red Bellpepper",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 36,
		name:  "Ribs",
		displayname:  "Ribs",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 37,
		name:  "Sake",
		displayname:  "Sake",
		price:  99.99,
		desc: "An incredible product.",
		category: "Beverages",
	},
	{
		id: 38,
		name:  "Sardines",
		displayname:  "Sardines",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 39,
		name:  "Sashimi",
		displayname:  "Sashimi",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 40,
		name:  "Shrimp",
		displayname:  "Shrimp",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 41,
		name:  "Steak",
		displayname:  "Steak",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 42,
		name:  "Strawberry",
		displayname:  "Strawberry",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 43,
		name:  "Sushi",
		displayname:  "Sushi",
		price:  99.99,
		desc: "An incredible product.",
		category: "Protein",
	},
	{
		id: 44,
		name:  "Tomato",
		displayname:  "Tomato",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 45,
		name:  "Turnip",
		displayname:  "Turnip",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 46,
		name:  "Waffle",
		displayname:  "Waffle",
		price:  99.99,
		desc: "An incredible product.",
		category: "Desserts/Sweets",
	},
	{
		id: 47,
		name:  "Watermelon",
		displayname:  "Watermelon",
		price:  99.99,
		desc: "An incredible product.",
		category: "Fruits/Vegetables",
	},
	{
		id: 48,
		name:  "Whiskey",
		displayname:  "Whiskey",
		price:  99.99,
		desc: "An incredible product.",
		category: "Beverages",
	},
	{
		id: 49,
		name:  "Wine",
		displayname:  "Wine",
		price:  99.99,
		desc: "An incredible product.",
		category: "Beverages",
	},
]

export default SampleProductsGen
